In [ ]:
import numpy as np
import matplotlib.pyplot as plt
#import arcpy
#from arcpy import env
from netCDF4 import Dataset
from matplotlib.path import Path
from scipy import interpolate
import copy
import pandas as pd
from matplotlib.colors import LinearSegmentedColormap
import sys
import os
from os.path import exists
import urllib
os.environ['PROJ_LIB']=r'C:\Users\JHurley\Anaconda3\pkgs\proj4-5.2.0-ha925a31_1\Library\share' ## location of epsg
#from arcpy.sa import *

#from arcpy.sa import *
#if arcpy.CheckExtension("Spatial") == "Available":
#    arcpy.CheckOutExtension("Spatial")

#from mpl_toolkits.basemap import Basemap

In [2]:
dafilename_ext=r"-2022-06-20-10-33.csv"

In [3]:
#### read in the data and reference data
refdafi=r"C:\Users\JHurley\avocado\mmerg_reform\Data_Source_MailMerge2.xlsx"
#indafi=r"C:\Users\JHurley\papaya\mmerg_reform\MailingList-2022-06-03-08-50.csv"
indafi=r'C:\Users\JHurley\avocado\mmerg_reform\MailingList'+dafilename_ext
refdata=pd.read_excel(refdafi)
data=pd.read_csv(indafi)
dataa=np.array(data)
data_fils=list(data.columns)
refdata_fils=list(refdata.columns)
data_filsa=np.array(data_fils)
refdata_filsa=np.array(refdata_fils)
data

MailingItemID  MailingID         APN  SuspectParcelStatusID  \
0          294092       1363  1300501000                      1   
1          294041       1363  1300501500                      1   
2          294056       1363  1320814100                      1   
3          294093       1363  1320814200                      1   
4          294087       1363  1320814400                      1   
..            ...        ...         ...                    ...   
68         294068       1363  1881003800                      1   
69         294066       1363  1881006800                      1   
70         294065       1363  1881006900                      1   
71         294064       1363  1881007000                      1   
72         294069       1363  1881007200                      1   

     CorrespondenceCode          CreationDate  IssueDate  ContactID  \
0   0035068-009-O-689E9  6/20/2022 5:33:49 PM        NaN      35068   
1   0035032-009-O-9DECE  6/20/2022 5:33:49 PM        NaN      35032   
2   0035045-009-O-3686B  6/20/2022 5:33:49 PM        NaN      35045   
3   0035053-009-O-21351  6/20/2022 5:33:49 PM        NaN      35053   
4   0035035-009-O-8C40C  6/20/2022 5:33:49 PM        NaN      35035   
..                  ...                   ...        ...        ...   
68  0035052-009-O-44C9C  6/20/2022 5:33:49 PM        NaN      35052   
69  0035052-009-O-44C9C  6/20/2022 5:33:49 PM        NaN      35052   
70  0035052-009-O-44C9C  6/20/2022 5:33:49 PM        NaN      35052   
71  0035052-009-O-44C9C  6/20/2022 5:33:49 PM        NaN      35052   
72  0035052-009-O-44C9C  6/20/2022 5:33:49 PM        NaN      35052   

    CreatorUser  ContactTypeName  ...  CareOf  StreetNumber  \
0         28485  Suspect Contact  ...     NaN           NaN   
1         28485  Suspect Contact  ...     NaN        5221.0   
2         28485  Suspect Contact  ...     NaN        9841.0   
3         28485  Suspect Contact  ...     NaN       29379.0   
4         28485  Suspect Contact  ...     NaN         468.0   
..          ...              ...  ...     ...           ...   
68        28485  Suspect Contact  ...     NaN        1728.0   
69        28485  Suspect Contact  ...     NaN        1728.0   
70        28485  Suspect Contact  ...     NaN        1728.0   
71        28485  Suspect Contact  ...     NaN        1728.0   
72        28485  Suspect Contact  ...     NaN        1728.0   

              StreetName  AptSuite  NormalizedFullStreetAddress  \
0             PO BOX 401       NaN                   PO BOX 401   
1              ARVADA ST       NaN               5221 ARVADA ST   
2     N THOUSAND OAKS CT       NaN      9841 N THOUSAND OAKS CT   
3   RANCHO CALIFORNIA RD       NaN   29379 RANCHO CALIFORNIA RD   
4            SURFVIEW DR       NaN              468 SURFVIEW DR   
..                   ...       ...                          ...   
68           OCEAN FRONT       NaN             1728 OCEAN FRONT   
69           OCEAN FRONT       NaN             1728 OCEAN FRONT   
70           OCEAN FRONT       NaN             1728 OCEAN FRONT   
71           OCEAN FRONT       NaN             1728 OCEAN FRONT   
72           OCEAN FRONT       NaN             1728 OCEAN FRONT   

             City  State    Zip CanSendCorrespondence PreferredAddress  
0    PAUMA VALLEY     CA  92061                                         
1        TORRANCE     CA  90503                                         
2          PEORIA     IL  61615                                         
3        TEMECULA     CA  92591                                         
4   PACIFIC PLSDS     CA  90272                                         
..            ...    ...    ...                   ...              ...  
68        DEL MAR     CA  92014                                         
69        DEL MAR     CA  92014                                         
70        DEL MAR     CA  92014                                         
71        DEL MAR     CA  92014                       

In [4]:
data_fils,refdata_fils

(['MailingItemID',
  'MailingID',
  'APN',
  'SuspectParcelStatusID',
  'CorrespondenceCode',
  'CreationDate',
  'IssueDate',
  'ContactID',
  'CreatorUser',
  'ContactTypeName',
  'FirstName',
  'LastName',
  'NormalizedFullName',
  'CareOf',
  'StreetNumber',
  'StreetName',
  'AptSuite',
  'NormalizedFullStreetAddress',
  'City',
  'State',
  'Zip',
  'CanSendCorrespondence',
  'PreferredAddress'],
 ['1Cert #### #### ####',
  '2Cert ####',
  '3Cert ####',
  'DATE_MAILED',
  'CorrespondenceCode',
  'Company',
  'NormalizedFullName',
  'OWNER_LAST',
  'OWNER_FIRST',
  'E-mail Address',
  'Job Title',
  'Business Phone',
  'Business Phone Extension#',
  'Home Phone',
  'Mobile Phone',
  'Fax Number',
  'NormalizedFullStreetAddress',
  'City',
  'State',
  'Dash',
  'Zip',
  'County',
  'Basin',
  'Country/Region',
  'Web Page',
  'Notes',
  'CareOf',
  'CO',
  'ZIP4_Old',
  'ZIP4',
  'Unit',
  'AptSuite',
  'APN 1',
  'APN 2',
  'APN 3',
  'APN 4',
  'APN 5',
  'APN 6',
  'APN 7',
  '

In [5]:
#### mapping datafilsa field column numbers to refdatafilsa field/column numbers
indxmap=np.ones((refdata_filsa.shape[0]))*-999
for i in np.arange(0,refdata_filsa.shape[0]):
    if refdata_filsa[i] in data_filsa:
        #print(refdata_filsa[i],np.where(data_filsa==refdata_filsa[i])[0][0])
        indxmap[i]=np.int(np.where(data_filsa==refdata_filsa[i])[0][0])
        
indxmap[indxmap==-999]=np.nan
apnindex=np.where(data_filsa=='APN')[0][0]

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


In [6]:
indxmap

array([nan, nan, nan, nan,  4., nan, 12., nan, nan, nan, nan, nan, nan,
       nan, nan, nan, 17., 18., 19., nan, 20., nan, nan, nan, nan, nan,
       13., nan, nan, nan, nan, 16., nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [7]:
ref_firstname_colno=np.where(refdata_filsa=='OWNER_FIRST')[0][0]
ref_lastname_colno=np.where(refdata_filsa=='OWNER_LAST')[0][0]
_firstname_colno=np.where(data_filsa=='FirstName')[0][0]
_lastname_colno=np.where(data_filsa=='LastName')[0][0]
print(ref_firstname_colno,ref_lastname_colno,_firstname_colno,_lastname_colno)
indxmap[ref_firstname_colno]=_firstname_colno
indxmap[ref_lastname_colno]=_lastname_colno

8 7 10 11


In [8]:
indxmap

array([nan, nan, nan, nan,  4., nan, 12., 11., 10., nan, nan, nan, nan,
       nan, nan, nan, 17., 18., 19., nan, 20., nan, nan, nan, nan, nan,
       13., nan, nan, nan, nan, 16., nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [9]:
if np.isnan(indxmap[0])==0:
    print('it is nan')

In [10]:
##### creates list of headers including apns and creates an empty array/dataframe
#del(corrcode_unqs_n)
corrcode_data_ix=np.where(data_filsa=='CorrespondenceCode')[0][0]
corrcode_unqs=np.unique(dataa[:,corrcode_data_ix])
corrcode_unqs_n=corrcode_unqs.shape[0]
idxs=[]
noapns=[]
for i in np.arange(0,corrcode_unqs_n):
    idxs.append(np.str(i))
    noapns.append(len(np.where(dataa[:,corrcode_data_ix]==corrcode_unqs[i])[0])) 
maxnoapns=np.nanmax(noapns)  ##### max number of apns per corr-code from list of APN # fields
apnlist=[]
for i in np.arange(0,maxnoapns):
    apnlist.append('APN '+np.str(i+1))
stdfilsix=(np.where(refdata_filsa=='APN 1')[0][0])-1
newfilslist=np.concatenate((refdata_filsa[0:stdfilsix],apnlist))
print(refdata_filsa[0:stdfilsix])
newdf=pd.DataFrame(columns=newfilslist,index=idxs)

newdf

['1Cert #### #### ####' '2Cert ####' '3Cert ####' 'DATE_MAILED'
 'CorrespondenceCode' 'Company' 'NormalizedFullName' 'OWNER_LAST'
 'OWNER_FIRST' 'E-mail Address' 'Job Title' 'Business Phone'
 'Business Phone Extension#' 'Home Phone' 'Mobile Phone' 'Fax Number'
 'NormalizedFullStreetAddress' 'City' 'State' 'Dash' 'Zip' 'County'
 'Basin' 'Country/Region' 'Web Page' 'Notes' 'CareOf' 'CO' 'ZIP4_Old'
 'ZIP4' 'Unit']


C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if __name__ == '__main__':
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\ipykernel_launcher.py:14: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


1Cert #### #### #### 2Cert #### 3Cert #### DATE_MAILED CorrespondenceCode  \
0                   NaN        NaN        NaN         NaN                NaN   
1                   NaN        NaN        NaN         NaN                NaN   
2                   NaN        NaN        NaN         NaN                NaN   
3                   NaN        NaN        NaN         NaN                NaN   
4                   NaN        NaN        NaN         NaN                NaN   
5                   NaN        NaN        NaN         NaN                NaN   
6                   NaN        NaN        NaN         NaN                NaN   
7                   NaN        NaN        NaN         NaN                NaN   
8                   NaN        NaN        NaN         NaN                NaN   
9                   NaN        NaN        NaN         NaN                NaN   
10                  NaN        NaN        NaN         NaN                NaN   
11                  NaN        NaN        NaN         NaN                NaN   
12                  NaN        NaN        NaN         NaN                NaN   
13                  NaN        NaN        NaN         NaN                NaN   
14                  NaN        NaN        NaN         NaN                NaN   
15                  NaN        NaN        NaN         NaN                NaN   
16                  NaN        NaN        NaN         NaN                NaN   
17                  NaN        NaN        NaN         NaN                NaN   
18                  NaN        NaN        NaN         NaN                NaN   
19                  NaN        NaN        NaN         NaN                NaN   
20                  NaN        NaN        NaN         NaN                NaN   
21                  NaN        NaN        NaN         NaN                NaN   
22                  NaN        NaN        NaN         NaN                NaN   
23                  NaN        NaN        NaN         NaN                NaN   
24                  NaN        NaN        NaN         NaN                NaN   
25                  NaN        NaN        NaN         NaN                NaN   
26                  NaN        NaN        NaN         NaN                NaN   
27                  NaN        NaN        NaN         NaN                NaN   
28                  NaN        NaN        NaN         NaN                NaN   
29                  NaN        NaN        NaN         NaN                NaN   
30                  NaN        NaN        NaN         NaN                NaN   
31                  NaN        NaN        NaN         NaN                NaN   
32                  NaN        NaN        NaN         NaN                NaN   
33                  NaN        NaN        NaN         NaN                NaN   
34                  NaN        NaN        NaN         NaN                NaN   
35                  NaN        NaN        NaN         NaN                NaN   
36                  NaN        NaN        NaN         NaN                NaN   
37                  NaN        NaN        NaN         NaN                NaN   
38                  NaN        NaN        NaN         NaN                NaN   
39                  NaN        NaN        NaN         NaN                NaN   
40                  NaN        NaN        NaN         NaN                NaN   
41                  NaN        NaN        NaN         NaN                NaN   
42                  NaN        NaN        NaN         NaN                NaN   
43                  NaN        NaN        NaN         NaN                NaN   
44                  NaN        NaN        NaN         NaN                NaN   
45                  NaN        NaN        NaN         NaN                NaN   
46                  NaN        NaN        NaN         NaN                NaN   
47                  NaN        NaN        NaN         NaN                NaN   
48                  NaN        NaN        NaN         NaN                NaN   
49 

In [11]:
#### filling the array or dataframe
for i in np.arange(0,corrcode_unqs_n):
    #idxs.append(np.str(i))
    tixs=np.array(np.where(dataa[:,corrcode_data_ix]==corrcode_unqs[i])[0])
    print(tixs,tixs.shape[0])
    for j in np.arange(0,newfilslist.shape[0]):
        #print(newfilslist[j])
        if np.isnan(indxmap[j])==0:
            #print(newdf.loc[np.str(i),newfilslist[j]],dataa[tixs[0],np.int(indxmap[j])])
            newdf.at[np.str(i),newfilslist[j]]=dataa[tixs[0],np.int(indxmap[j])]
            #print(newdf.loc[np.str(i),newfilslist[j]])
        ### find matching field/col-name from datasource and put value in newdf with newdf.at[ind,col]
    for k in np.arange(0,tixs.shape[0]):
        #print(np.str(i),np.str('APN '+np.str(k)))
        newdf.at[np.str(i),np.str('APN '+np.str(k+1))]=dataa[tixs[k],apnindex]
        #print(tixs[k])
        #print(np.where(dataa[:,corrcode_data_ix]==corrcode_unqs[i])[0])

[1] 1
[20 21 35] 3
[34] 1
[4 5 6] 3
[11 14] 2
[43] 1
[16 17] 2
[44 45 46] 3
[31 32] 2
[58 64] 2
[57] 1
[62] 1
[48 65] 2
[2] 1
[18] 1
[25] 1
[49] 1
[66 67] 2
[60 61] 2
[47] 1
[68 69 70 71 72] 5
[3 9] 2
[7 8] 2
[56] 1
[63] 1
[55] 1
[50] 1
[59] 1
[29] 1
[10] 1
[15] 1
[13] 1
[53] 1
[42] 1
[38 39 51] 3
[33] 1
[0] 1
[37] 1
[36] 1
[22] 1
[28] 1
[27] 1
[54] 1
[52] 1
[26 40 41] 3
[23] 1
[24] 1
[12] 1
[19] 1
[30] 1


C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  # Remove the CWD from sys.path while we load stuff.
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Depreca

In [12]:
#newdf.at[np.str(i),np.str('APN '+np.str(k))]
#np.str(i),np.str('APN '+np.str(k+1)),newfilslist
newdf

1Cert #### #### #### 2Cert #### 3Cert #### DATE_MAILED  \
0                   NaN        NaN        NaN         NaN   
1                   NaN        NaN        NaN         NaN   
2                   NaN        NaN        NaN         NaN   
3                   NaN        NaN        NaN         NaN   
4                   NaN        NaN        NaN         NaN   
5                   NaN        NaN        NaN         NaN   
6                   NaN        NaN        NaN         NaN   
7                   NaN        NaN        NaN         NaN   
8                   NaN        NaN        NaN         NaN   
9                   NaN        NaN        NaN         NaN   
10                  NaN        NaN        NaN         NaN   
11                  NaN        NaN        NaN         NaN   
12                  NaN        NaN        NaN         NaN   
13                  NaN        NaN        NaN         NaN   
14                  NaN        NaN        NaN         NaN   
15                  NaN        NaN        NaN         NaN   
16                  NaN        NaN        NaN         NaN   
17                  NaN        NaN        NaN         NaN   
18                  NaN        NaN        NaN         NaN   
19                  NaN        NaN        NaN         NaN   
20                  NaN        NaN        NaN         NaN   
21                  NaN        NaN        NaN         NaN   
22                  NaN        NaN        NaN         NaN   
23                  NaN        NaN        NaN         NaN   
24                  NaN        NaN        NaN         NaN   
25                  NaN        NaN        NaN         NaN   
26                  NaN        NaN        NaN         NaN   
27                  NaN        NaN        NaN         NaN   
28                  NaN        NaN        NaN         NaN   
29                  NaN        NaN        NaN         NaN   
30                  NaN        NaN        NaN         NaN   
31                  NaN        NaN        NaN         NaN   
32                  NaN        NaN        NaN         NaN   
33                  NaN        NaN        NaN         NaN   
34                  NaN        NaN        NaN         NaN   
35                  NaN        NaN        NaN         NaN   
36                  NaN        NaN        NaN         NaN   
37                  NaN        NaN        NaN         NaN   
38                  NaN        NaN        NaN         NaN   
39                  NaN        NaN        NaN         NaN   
40                  NaN        NaN        NaN         NaN   
41                  NaN        NaN        NaN         NaN   
42                  NaN        NaN        NaN         NaN   
43                  NaN        NaN        NaN         NaN   
44                  NaN        NaN        NaN         NaN   
45                  NaN        NaN        NaN         NaN   
46                  NaN        NaN        NaN         NaN   
47                  NaN        NaN        NaN         NaN   
48                  NaN        NaN        NaN         NaN   
49                  NaN        NaN        NaN         NaN   

     CorrespondenceCode Company              NormalizedFullName OWNER_LAST  \
0   0035032-009-O-9DECE     NaN                         TAKASHI        NaN   
1   0035033-009-O-F6DC3     NaN                       KENNETH D        NaN   
2   0035034-009-O-2BD24     NaN                            JOSE        NaN   
3   0035035-009-O-8C40C     NaN                 MATTHEW MEHRBOD        NaN   
4   0035036-009-O-69DA0     NaN  PALOMAR MOUNTAIN GRANITE SPRIN        NaN   
5   0035037-009-O-AE7EE     NaN                     KEVIN DAVID        NaN   
6   0035038-009-O-3C598     NaN                           BARRY        NaN   
7   0035039-009-O-F16BA     NaN             BELL HOLDINGS L L C        NaN   
8   0035040-009-O-E0067     NaN              QUAILNUT ACRES LLC        NaN   
9   0035041-009-O-C200E     NaN                          MARK R        NaN   
10  0035042-009-O-15AE9     NaN  

In [13]:
#### saves array/dataframe to file csv
oudafi=r'C:\Users\JHurley\avocado\mmerg_reform\reformed_wadd'+dafilename_ext
newdf.to_csv(oudafi)